version: 3.0.{build}.0
image: Visual Studio 2017
install:
- cmd: git submodule -q update --init
before_build:
- nuget restore Indicium-Supra.sln
build_script:
- ps: .\build.ps1 -configuration release
after_build:
- ps: |
    Invoke-WebRequest "https://downloads.vigem.org/other/pavel-a/ddverpatch/verpatch-1.0.15.1-x86-codeplex.zip" -OutFile verpatch-1.0.15.1-x86-codeplex.zip
    Expand-Archive verpatch-1.0.15.1-x86-codeplex.zip -DestinationPath .
    .\verpatch.exe .\bin\x64\Indicium-FW1FontWrapper.Plugin.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\Indicium-FW1FontWrapper.Plugin.dll /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\Indicium-ImGui.Plugin.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\Indicium-ImGui.Plugin.dll /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\Indicium-Supra.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\Indicium-Supra.dll /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-FW1FontWrapper.Plugin.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-FW1FontWrapper.Plugin.dll /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-ImGui.Plugin.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-ImGui.Plugin.dll /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-Supra.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-Supra.dll /pv "$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: 'bin\**\*.dll'
  name: Indicium-Supra
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true